apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: book-service
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: book-service
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s